theme = 'catppuccin_macchiato'

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
p = "paste_before"
P = "paste_after"
X = "extend_line_above"
"minus" = "select_register"

[keys.normal.g]
x = ":buffer-close"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
p = "paste_clipboard_before"
P = "paste_clipboard_after"

[keys.select]
A-s = [":pipe sort"]

[keys.normal.space.","]
y = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash helix-yazi-zellij open"
g = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- gitui -t macchiato.ron"
