
[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.9
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/keybinds.toml"
]
