name: Bug Report
description: Report a bug or issue with the DWM config, patches, or setup scripts.
title: "[Bug]: "
labels: ["bug"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve the DWM config! Please provide as much detail as possible.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |

        Please describe the issue. What did you expect to happen, and what actually happened?
      placeholder: When I did X, Y happened, but I expected Z.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: |

        Provide the steps or commands to reproduce the issue. Include any relevant configurations or scripts.
      placeholder: Step-by-step instructions to reproduce the issue.
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: On which environment are you using the DWM config?
      multiple: false
      options:
        - Arch Linux
        - Arch-based Distro
        - Debian
        - Fedora
        - openSUSE
        - Other
    validations:
      required: true
    default: Arch Linux
  - type: input
    id: specify-environment
    attributes:
      label: Specify the environment
      description: |

        If you selected "Other," please specify the environment you're using.
      placeholder: e.g., Void Linux, Gentoo, etc.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/harilvfs/dwm/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

