#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Timeshift Recovery (2025-04-02)" {
    set root=(hd0,3)
    linux /timeshift/snapshots/2025-04-02_22-20-49/localhost/boot/vmlinuz-linux-cachyos root=UUID=7284b62c-7830-4163-aad7-1bac5b4054b5 rw
    initrd /timeshift/snapshots/2025-04-02_22-20-49/localhost/boot/initramfs-linux-cachyos.img
}
